name: Validate PR
on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Validate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component-directory:
         - "./AutoWidthLabel"
         - "./Breadcrumb" 
         - "./Calendar" 
         - "./CommandBar" 
         - "./ContextMenu" 
         - "./DetailsList" 
         - "./DonutChart" 
         - "./Elevation" 
         - "./Facepile"
         - "./GaugeChart"
         - "./HorizontalBarChart"
         - "./Icon"
         - "./KeyboardShortcuts"
         - "./Nav"
         - "./PeoplePicker"
         - "./Persona"
         - "./Picker"
         - "./Pivot"
         - "./ProgressIndicator"
         - "./ResizableTextarea"
         - "./SearchBox"
         - "./Shimmer"
         - "./SpinButton"
         - "./Spinner"
         - "./StackedBarChart"
         - "./SubwayNav"
         - "./TagList"
         - "./ThemeGenerator"

    defaults:
      run:
        working-directory: ${{ matrix.component-directory }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '18.x'
    - name: Install dependencies
      run: npm ci
    - run: npm run build
    - run: npm test
